package block

const (
	TraitPlacementDirection string = "minecraft:placement_direction"
	TraitPlacementPosition  string = "minecraft:placement_position"
)

const (
	PlacementDirectionCardinal string = "minecraft:cardinal_direction"
	PlacementDirectionFacing   string = "minecraft:facing_direction"
)

const (
	PlacementPositionBlockFace string = "minecraft:block_face"
	PlacementPositionVertical  string = "minecraft:vertical_half"
)

const (
	GroupAnvil             string = "itemGroup.name.anvil"
	GroupArrow             string = "itemGroup.name.arrow"
	GroupAxe               string = "itemGroup.name.axe"
	GroupBanner            string = "itemGroup.name.banner"
	GroupBannerPattern     string = "itemGroup.name.banner_pattern"
	GroupBed               string = "itemGroup.name.bed"
	GroupBoat              string = "itemGroup.name.boat"
	GroupBoots             string = "itemGroup.name.boots"
	GroupButtons           string = "itemGroup.name.buttons"
	GroupCandles           string = "itemGroup.name.candles"
	GroupChalkboard        string = "itemGroup.name.chalkboard"
	GroupChest             string = "itemGroup.name.chest"
	GroupChestboat         string = "itemGroup.name.chestboat"
	GroupChestplate        string = "itemGroup.name.chestplate"
	GroupConcrete          string = "itemGroup.name.concrete"
	GroupConcretePowder    string = "itemGroup.name.concretePowder"
	GroupCookedFood        string = "itemGroup.name.cookedFood"
	GroupCopper            string = "itemGroup.name.copper"
	GroupCoral             string = "itemGroup.name.coral"
	GroupCoralDecorations  string = "itemGroup.name.coral_decorations"
	GroupCrop              string = "itemGroup.name.crop"
	GroupDoor              string = "itemGroup.name.door"
	GroupDye               string = "itemGroup.name.dye"
	GroupEnchantedBook     string = "itemGroup.name.enchantedBook"
	GroupFence             string = "itemGroup.name.fence"
	GroupFenceGate         string = "itemGroup.name.fenceGate"
	GroupFirework          string = "itemGroup.name.firework"
	GroupFireworkStars     string = "itemGroup.name.fireworkStars"
	GroupFlower            string = "itemGroup.name.flower"
	GroupGlass             string = "itemGroup.name.glass"
	GroupGlassPane         string = "itemGroup.name.glassPane"
	GroupGlazedTerracotta  string = "itemGroup.name.glazedTerracotta"
	GroupGoatHorn          string = "itemGroup.name.goatHorn"
	GroupGrass             string = "itemGroup.name.grass"
	GroupHangingSign       string = "itemGroup.name.hanging_sign"
	GroupHelmet            string = "itemGroup.name.helmet"
	GroupHoe               string = "itemGroup.name.hoe"
	GroupHorseArmor        string = "itemGroup.name.horseArmor"
	GroupLeaves            string = "itemGroup.name.leaves"
	GroupLeggings          string = "itemGroup.name.leggings"
	GroupLingeringPotion   string = "itemGroup.name.lingeringPotion"
	GroupLog               string = "itemGroup.name.log"
	GroupMinecart          string = "itemGroup.name.minecart"
	GroupMiscFood          string = "itemGroup.name.miscFood"
	GroupMobEgg            string = "itemGroup.name.mobEgg"
	GroupMonsterStoneEgg   string = "itemGroup.name.monsterStoneEgg"
	GroupMushroom          string = "itemGroup.name.mushroom"
	GroupNetherWartBlock   string = "itemGroup.name.netherWartBlock"
	GroupOre               string = "itemGroup.name.ore"
	GroupPermission        string = "itemGroup.name.permission"
	GroupPickaxe           string = "itemGroup.name.pickaxe"
	GroupPlanks            string = "itemGroup.name.planks"
	GroupPotion            string = "itemGroup.name.potion"
	GroupPotterySherds     string = "itemGroup.name.potterySherds"
	GroupPressurePlate     string = "itemGroup.name.pressurePlate"
	GroupRail              string = "itemGroup.name.rail"
	GroupRawFood           string = "itemGroup.name.rawFood"
	GroupRecord            string = "itemGroup.name.record"
	GroupSandstone         string = "itemGroup.name.sandstone"
	GroupSapling           string = "itemGroup.name.sapling"
	GroupSculk             string = "itemGroup.name.sculk"
	GroupSeed              string = "itemGroup.name.seed"
	GroupShovel            string = "itemGroup.name.shovel"
	GroupShulkerBox        string = "itemGroup.name.shulkerBox"
	GroupSign              string = "itemGroup.name.sign"
	GroupSkull             string = "itemGroup.name.skull"
	GroupSlab              string = "itemGroup.name.slab"
	GroupSmithingTemplates string = "itemGroup.name.smithing_templates"
	GroupSplashPotion      string = "itemGroup.name.splashPotion"
	GroupStainedClay       string = "itemGroup.name.stainedClay"
	GroupStairs            string = "itemGroup.name.stairs"
	GroupStone             string = "itemGroup.name.stone"
	GroupStoneBrick        string = "itemGroup.name.stoneBrick"
	GroupSword             string = "itemGroup.name.sword"
	GroupTrapdoor          string = "itemGroup.name.trapdoor"
	GroupWalls             string = "itemGroup.name.walls"
	GroupWood              string = "itemGroup.name.wood"
	GroupWool              string = "itemGroup.name.wool"
	GroupWoolCarpet        string = "itemGroup.name.woolCarpet"
)
