package component

// Code generated by scrapper/block.ts;

// determines whether the block is breathable by defining if the block is treated as a solid or as air. Experimental toggles required: Holiday Creator Features.
type Breathability string
