package component

// Code generated by scrapper/block.ts;

// Defines the area of the block that collides with entities. If set to true, default values are used. If set to false, the block's collision with entities is disabled. If this component is omitted, default values are used. Experimental toggles required: Holiday Creator Features (in format versions before 1.19.50).
type CollisionBox struct {
	// Minimal position of the bounds of the collision box. origin is specified as [x, y, z] and must be in the range (-8, 0, -8) to (8, 16, 8), inclusive.
	Origin []float64 `json:"origin,omitempty"`

	// Size of each side of the collision box. Size is specified as [x, y, z]. origin + size must be in the range (-8, 0, -8) to (8, 16, 8), inclusive.
	Size []float64 `json:"size,omitempty"`
}
