package component

// Code generated by scrapper/block.ts;

// Specifies the language file key that maps to what text will be displayed when you hover over the block in your inventory and hotbar. If the string given can not be resolved as a loc string, the raw string given will be displayed. If this component is omitted, the name of the block will be used as the display name. Experimental toggles required: Holiday Creator Features (in format versions before 1.19.60).
type DisplayName string
