package component

// Code generated by scrapper/block.ts;

// Describes the friction for this block in a range of (0.0-0.9). Friction affects an entity's movement speed when it travels on the block. Greater value results in more friction.
type Friction float32
