package component

// Code generated by scrapper/block.ts;

// The description identifier of the geometry file to use to render this block. This identifier must match an existing geometry identifier in any of the currently loaded resource packs. Experimental toggles required: Holiday Creator Features (in format versions before 1.19.40).
type Geometry struct {
	Identifier     string          `json:"identifier,omitempty"`
	BoneVisibility map[string]bool `json:"bone_visibility,omitempty"`
}
