package component

// Code generated by scrapper/block.ts;

// The amount that light will be dampened when it passes through the block, in a range (0-15). Higher value means the light will be dampened more.
type LightDampening int
