package component

// Code generated by scrapper/block.ts;

// The material instances for a block. Maps face or material_instance names in a geometry file to an actual material instance. You can assign a material instance object to any of these faces: "up", "down", "north", "south", "east", "west", or "*". You can also give an instance the name of your choosing such as "my_instance", and then assign it to a face by doing "north":"my_instance". Experimental toggles required: Holiday Creator Features (in format versions before 1.19.40).
type MaterialInstance map[string]*MaterialInstanceParameter

// The following are parameters of EACH material instance you provide:
type MaterialInstanceParameter struct {
	// Should this material have ambient occlusion applied when lighting? If true, shadows will be created around and underneath the block.
	AmbientOcclusion bool `json:"ambient_occlusion,omitempty"`

	// Should this material be dimmed by the direction it's facing?
	FaceDimming bool `json:"face_dimming,omitempty"`

	// The render method to use. Must be one of these options:
	//  - opaque - Used for a regular block texture without an alpha layer. Does not allow for transparency or translucency.
	//  - double_sided - Used for completely disabling backface culling.
	//  - blend - Used for a block like stained glass. Allows for transparency and translucency (slightly transparent textures).
	//  - alpha_test - Used for a block like the vanilla (unstained) glass. Does not allow for translucency, only fully opaque or fully transparent textures. Also disables backface culling.
	RenderMethod string `json:"render_method,omitempty"`

	// Texture name for the material.
	Texture string `json:"texture,omitempty"`
}
