package component

// Code generated by scrapper/block.ts;

// Defines the area of the block that is selected by the player's cursor. If set to true, default values are used. If set to false, this block is not selectable by the player's cursor. If this component is omitted, default values are used. Experimental toggles required: Holiday Creator Features (in format versions before 1.19.60).
type SelectionBox struct {
	// Minimal position of the bounds of the selection box. "origin" is specified as [x, y, z] and must be in the range (-8, 0, -8) to (8, 16, 8), inclusive.
	Origin []float64 `json:"origin,omitempty"`

	// Size of each side of the selection box. Size is specified as [x, y, z]. "origin" + "size" must be in the range (-8, 0, -8) to (8, 16, 8), inclusive.
	Size []float64 `json:"size,omitempty"`
}
