package component

// Code generated by scrapper/block.ts;

// The block's translation around the center of the cube in degrees. The rotation order is [x, y, z]. Angles need to be in multiples of 90. Experimental toggles required: Holiday Creator Features (in format versions before 1.19.80).
type Transformation struct {
	Translation []float64 `json:"translation,omitempty"`
	Scale       []float64 `json:"scale,omitempty"`
	Rotation    []float64 `json:"rotation,omitempty"`
}
