package component

// Code generated by scrapper/entityBp.ts;

// Adds a rider to the entity. Requires minecraft:rideable.  
type Addrider struct {
  // The entity type that will be riding this entity.
  EntityType string `json:"entity_type,omitempty"`
  // The spawn event that will be used when the riding entity is created.
  SpawnEvent string `json:"spawn_event,omitempty"`
}
