package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// Adds a timer for the entity to grow up. It can be accelerated by giving the entity the items it likes as defined by feedItems.  
type Ageable struct {
  // List of items that the entity drops when it grows up.
  DropItems []interface{} `json:"drop_items,omitempty"`
  // Amount of time before the entity grows up, -1 for always a baby.
  Duration *float64 `json:"duration,omitempty"`
  // List of items that can be fed to the entity. Includes 'item' for the item name and 'growth' to define how much time it grows up by.
  FeedItems []interface{} `json:"feed_items,omitempty"`
  // Event to run when this entity grows up.
  GrowUp string `json:"grow_up,omitempty"`
  // List of conditions to meet so that the entity can be fed.
  InteractFilters *f.Filter `json:"interact_filters,omitempty"`
  // The feed item used will transform to this item upon successful interaction. Format: itemName:auxValue
  TransformToItem string `json:"transform_to_item,omitempty"`
}
