package component

// Code generated by scrapper/entityBp.ts;

// Allows the actor to open doors assuming that that flags set up for the component to use in navigation
type Annotation_OpenDoor struct {
}
