package component

// Code generated by scrapper/entityBp.ts;

// Defines an entity's melee attack and any additional effects on it.  
type Attack struct {
  // Range of the random amount of damage the melee attack deals. A negative value can heal the entity instead of hurting it
  Damage float64 `json:"damage,omitempty"`
  // Duration in seconds of the status ailment applied to the damaged entity
  EffectDuration float64 `json:"effect_duration,omitempty"`
  // Identifier of the status ailment to apply to an entity attacked by this entity's melee attack
  EffectName string `json:"effect_name,omitempty"`
}
