package component

// Code generated by scrapper/entityBp.ts;

// Enables the component to drop an item as a barter exchange.  
type Barter struct {
  // Loot table that's used to drop a random item.
  BarterTable string `json:"barter_table,omitempty"`
  // Duration, in seconds, for which mob won't barter items if it was hurt
  CooldownAfterBeingAttacked int `json:"cooldown_after_being_attacked,omitempty"`
}
