package component

// Code generated by scrapper/entityBp.ts;

// Allows this entity to avoid certain blocks.  
type Behavior_AvoidBlock struct {
  // The sound event to play when the mob is avoiding a block.
  AvoidBlockSound string `json:"avoid_block_sound,omitempty"`
  // [Trigger] Escape trigger.
  OnEscape interface{} `json:"on_escape,omitempty"`
  // Maximum distance to look for a block in y.
  SearchHeight int `json:"search_height,omitempty"`
  // Maximum distance to look for a block in xz.
  SearchRange int `json:"search_range,omitempty"`
  // The range of time in seconds to randomly wait before playing the sound again.
  SoundInterval float64 `json:"sound_interval,omitempty"`
  // Modifier for sprint speed. 1.0 means keep the regular speed, while higher numbers make the sprint speed faster.
  SprintSpeedModifier float64 `json:"sprint_speed_modifier,omitempty"`
  // List of block types this mob avoids.
  TargetBlocks []interface{} `json:"target_blocks,omitempty"`
  // Block search method.
  TargetSelectionMethod string `json:"target_selection_method,omitempty"`
  // Should start tick interval.
  TickInterval int `json:"tick_interval,omitempty"`
  // Modifier for walking speed. 1.0 means keep the regular speed, while higher numbers make the walking speed faster.
  WalkSpeedModifier float64 `json:"walk_speed_modifier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
