package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to go into stone blocks like Silverfish do. Currently it can only be used by Silverfish.
type Behavior_SilverfishMergeWithStone struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
