package component

// Code generated by scrapper/entityBp.ts;

// Allows mob to move towards its current target.  
type Behavior_MoveTowardsTarget struct {
  // Defines the radius in blocks that the mob tries to be from the target. A value of 0 means it tries to occupy the same block as the target
  WithinRadius float64 `json:"within_radius,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
