package component

// Code generated by scrapper/entityBp.ts;

// [EXPERIMENTAL] Allows this entity to rise for a specified duration  
type Behavior_Rising struct {
  // Goal cooldown range in seconds
  CooldownRange float64 `json:"cooldown_range,omitempty"`
  // Goal duration range in seconds
  DurationRange float64 `json:"duration_range,omitempty"`
  // [Trigger] Event(s) to run when the goal end.
  OnEnd interface{} `json:"on_end,omitempty"`
  // [Trigger] Event(s) to run when the goal starts.
  OnStart interface{} `json:"on_start,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
