package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to peek out. This is what the shulker uses to look out of its shell.
type Behavior_Peek struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
