package component

// Code generated by scrapper/entityBp.ts;

// Allows this entity to roar at another entity based on data in minecraft:anger_level. Once the anger threshold specified in minecraft:anger_level has been reached, this entity will roar for the specified amount of time, look at the other entity, apply anger boost towards it, and finally target it.  
type Behavior_Roar struct {
  // The amount of time to roar for.
  Duration float64 `json:"duration,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
