package component

// Code generated by scrapper/entityBp.ts;

// Allows the a mob to become scared when the weather outside is thundering  
type Behavior_Scared struct {
  // The interval in which a sound will play when active in a 1/delay chance to kick off
  SoundInterval int `json:"sound_interval,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
