package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to stay put while it is in a sitting state instead of doing something else.
type Behavior_StayWhileSitting struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
