package component

// Code generated by scrapper/entityBp.ts;

// Allows the squid to dive down in water. Can only be used by the Squid.
type Behavior_SquidDive struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
