package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to open doors. Requires the mob to be able to path through doors, otherwise the mob won't even want to try opening them.  
type Behavior_OpenDoor struct {
  // If true, the mob will close the door after opening it and going through it
  CloseDoorAfter bool `json:"close_door_after,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
