package component

// Code generated by scrapper/entityBp.ts;

// Allows the dragon to go out with glory. This controls the Ender Dragon's death animation and can't be used by other mobs.
type Behavior_Dragondeath struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
