package component

// Code generated by scrapper/entityBp.ts;

// This allows the mob to roll forward.  
type Behavior_Roll struct {
  // The probability that the mob will use the goal.
  Probability float64 `json:"probability,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
