package component

// Code generated by scrapper/entityBp.ts;

// Allows the wither to launch random attacks. Can only be used by the Wither Boss.
type Behavior_WitherRandomAttackPosGoal struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
