package component

// Code generated by scrapper/entityBp.ts;

// Allows the enderman to drop a block they are carrying. Can only be used by Endermen.
type Behavior_EndermanLeaveBlock struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
