package component

// Code generated by scrapper/entityBp.ts;

// Allows the Dragon to stop flying and transition into perching mode. Can only be used by the Ender Dragon.
type Behavior_Dragonlanding struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
