package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to hover around randomly, close to the surface  
type Behavior_RandomHover struct {
  // The height above the surface which the mob will try to maintain
  HoverHeight float64 `json:"hover_height,omitempty"`
  // A random value to determine when to randomly move somewhere. This has a 1/interval chance to choose this goal
  Interval *int `json:"interval,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // Distance in blocks on ground that the mob will look for a new spot to move to. Must be at least 1
  XzDist *int `json:"xz_dist,omitempty"`
  // Distance in blocks that the mob will look up or down for a new spot to move to. Must be at least 1
  YDist *int `json:"y_dist,omitempty"`
  // Height in blocks to add to the selected target position
  YOffset float64 `json:"y_offset,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
