package component

// Code generated by scrapper/entityBp.ts;

// Allows the dragon to leave perch mode and go back to flying around. Can only be used by the Ender Dragon.
type Behavior_Dragontakeoff struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
