package component

// Code generated by scrapper/entityBp.ts;

// Allows the NPC to use the POI  
type Behavior_Work struct {
  // The amount of ticks the NPC will stay in their the work location
  ActiveTime int `json:"active_time,omitempty"`
  // If true, this entity can work when their jobsite POI is being rained on.
  CanWorkInRain bool `json:"can_work_in_rain,omitempty"`
  // The amount of ticks the goal will be on cooldown before it can be used again
  GoalCooldown int `json:"goal_cooldown,omitempty"`
  // [Trigger] Event to run when the mob reaches their jobsite.
  OnArrival interface{} `json:"on_arrival,omitempty"`
  // The max interval in which a sound will play.
  SoundDelayMax int `json:"sound_delay_max,omitempty"`
  // The min interval in which a sound will play.
  SoundDelayMin int `json:"sound_delay_min,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // If "can_work_in_rain" is false, this is the maximum number of ticks left in the goal where rain will not interrupt the goal
  WorkInRainTolerance *int `json:"work_in_rain_tolerance,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
