package component

// Code generated by scrapper/entityBp.ts;

// Allows the entity to wander around while swimming, when not path-finding.  
type Behavior_SwimWander struct {
  // Percent chance to start wandering, when not path-finding. 1 = 100%
  Interval float64 `json:"interval,omitempty"`
  // Distance to look ahead for obstacle avoidance, while wandering.
  LookAhead float64 `json:"look_ahead,omitempty"`
  // This multiplier modifies the entity's speed when wandering.
  SpeedMultiplier float64 `json:"speed_multiplier,omitempty"`
  // Amount of time (in seconds) to wander after wandering behavior was successfully started.
  WanderTime float64 `json:"wander_time,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
