package component

// Code generated by scrapper/entityBp.ts;

// Allows the Dragon to fly around in a circle around the center podium. Can only be used by the Ender Dragon.
type Behavior_Dragonholdingpattern struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
