package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// [Not a component] A list of potions that this entity can drink. Each potion entry has the following parameters:
type BehaviorDrinkPotionPotions struct {
  // The percent chance (from 0.0 to 1.0) of this potion being selected when searching for a potion to use.
  Chance *float64 `json:"chance,omitempty"`
  // The filters to use when determining if this potion can be selected.
  Filters *f.Filter `json:"filters,omitempty"`
  // The registry ID of the potion to use
  Id *int `json:"id,omitempty"`
}

// Allows the mob to drink potions based on specified environment conditions.  
type Behavior_DrinkPotion struct {
  // A list of potions that this entity can drink. Each potion entry has the following parameters:
  Potions []BehaviorDrinkPotionPotions `json:"potions,omitempty"`
  // The movement speed modifier to apply to the entity while it is drinking a potion. A value of 0 represents no change in speed.
  SpeedModifier float64 `json:"speed_modifier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
