package component

// Code generated by scrapper/entityBp.ts;

// Allows this entity to detect the nearest player within "sniffing_radius" and update its "minecraft:suspect_tracking" component state  
type Behavior_Sniff struct {
  // Cooldown range between sniffs in seconds
  CooldownRange float64 `json:"cooldown_range,omitempty"`
  // Sniffing duration in seconds
  Duration float64 `json:"duration,omitempty"`
  // Mob detection radius
  SniffingRadius float64 `json:"sniffing_radius,omitempty"`
  // Mob suspicion horizontal radius. When a player is within this radius horizontally, the anger level towards that player is increased
  SuspicionRadiusHorizontal float64 `json:"suspicion_radius_horizontal,omitempty"`
  // Mob suspicion vertical radius. When a player is within this radius vertically, the anger level towards that player is increased
  SuspicionRadiusVertical float64 `json:"suspicion_radius_vertical,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
