package component

// Code generated by scrapper/entityBp.ts;

// Allows the squid to swim away. Can only be used by the Squid.
type Behavior_SquidFlee struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
