package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to alert mobs in nearby blocks to come out. Currently it can only be used by Silverfish.
type Behavior_SilverfishWakeUpFriends struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
