package component

// Code generated by scrapper/entityBp.ts;

// Allows monsters to jump at and attack their target. Can only be used by hostile mobs.  
type Behavior_LeapAtTarget struct {
  // If true, the mob will only jump at its target if its on the ground. Setting it to false will allow it to jump even if its already in the air
  MustBeOnGround bool `json:"must_be_on_ground,omitempty"`
  // Allows the actor to be set to persist upon targeting a player
  SetPersistent bool `json:"set_persistent,omitempty"`
  // The height in blocks the mob jumps when leaping at its target
  Yd float64 `json:"yd,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
