package component

// Code generated by scrapper/entityBp.ts;

// Allows an entity to go to the village bell and mingle with other entities  
type Behavior_Mingle struct {
  // Time in seconds the mob has to wait before using the goal again
  CooldownTime float64 `json:"cooldown_time,omitempty"`
  // Amount of time in seconds that the entity will chat with another entity
  Duration *float64 `json:"duration,omitempty"`
  // The distance from its partner that this entity will mingle. If the entity type is not the same as the entity, this value needs to be identical on both entities.
  MingleDistance *float64 `json:"mingle_distance,omitempty"`
  // The entity type that this entity is allowed to mingle with
  MinglePartnerType *[]interface{} `json:"mingle_partner_type,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
