package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to stay afloat while swimming. Passengers will be kicked out the moment the mob's head goes underwater, which may not happen for tall mobs.  
type Behavior_Float struct {
  // If true, the mob will keep sinking as long as it has passengers.
  SinkWithPassengers bool `json:"sink_with_passengers,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
