package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to move around randomly like the Vex.
type Behavior_VexRandomMove struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
