package component

// Code generated by scrapper/entityBp.ts;

// Allows the villager to look for a mate to spawn other villagers with. Can only be used by Villagers.
type Behavior_MakeLove struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
