package component

// Code generated by scrapper/entityBp.ts;

// Allows the villager to stop so another villager can breed with it. Can only be used by a Villager.
type Behavior_ReceiveLove struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
