package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to play with other mobs by chasing each other and moving around randomly.  
type Behavior_Play struct {
  // Percent chance that the mob will start this goal, from 0 to 1.
  ChanceToStart *float64 `json:"chance_to_start,omitempty"`
  // The distance (in blocks) that the mob tries to be in range of the friend it's following.
  FollowDistance *int `json:"follow_distance,omitempty"`
  // [Vector3 [a,b,c]] The dimensions of the AABB used to search for a potential friend to play with.
  FriendSearchArea *[]float64 `json:"friend_search_area,omitempty"`
  // The entity type(s) to consider when searching for a potential friend to play with.
  FriendTypes []interface{} `json:"friend_types,omitempty"`
  // The max amount of seconds that the mob will play for before exiting the Goal.
  MaxPlayDurationSeconds *float64 `json:"max_play_duration_seconds,omitempty"`
  // The height (in blocks) that the mob will search within to find a random position position to move to. Must be at least 1.
  RandomPosSearchHeight *int `json:"random_pos_search_height,omitempty"`
  // The distance (in blocks) on ground that the mob will search within to find a random position to move to. Must be at least 1.
  RandomPosSearchRange *int `json:"random_pos_search_range,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal.
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
