package component

// Code generated by scrapper/entityBp.ts;

// Allows the entity to stay in a village and defend the village from aggressors. If a player is in bad standing with the village this goal will cause the entity to attack the player regardless of filter conditions.  
type Behavior_DefendVillageTarget struct {
  // The percentage chance that the entity has to attack aggressors of its village, where 1.0 = 100%.
  AttackChance float64 `json:"attack_chance,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
