package component

// Code generated by scrapper/entityBp.ts;

// Allows this entity to fly around looking for a player to shoot fireballs at. Can only be used by the Ender Dragon.  
type Behavior_Dragonstrafeplayer struct {
  // The speed this entity moves when this behavior has started or while it's active.
  ActiveSpeed float64 `json:"active_speed,omitempty"`
  // Maximum distance of this entity's fireball attack while strafing.
  FireballRange float64 `json:"fireball_range,omitempty"`
  // The speed this entity moves while this behavior is not active.
  FlightSpeed float64 `json:"flight_speed,omitempty"`
  // Percent chance to to switch this entity's strafe direction between clockwise and counterclockwise. Switch direction chance occurs each time a new target is chosen (1.0 = 100%).
  SwitchDirectionProbability float64 `json:"switch_direction_probability,omitempty"`
  // Time (in seconds) the target must be in fireball range, and in view [ie, no solid terrain in-between the target and this entity], before a fireball can be shot.
  TargetInRangeAndInViewTime float64 `json:"target_in_range_and_in_view_time,omitempty"`
  // Minimum and maximum distance, from the target, this entity can use this behavior.
  TargetZone float64 `json:"target_zone,omitempty"`
  // The speed at which this entity turns while using this behavior.
  TurnSpeed float64 `json:"turn_speed,omitempty"`
  // The target must be within "view_angle" degrees of the dragon's current rotation before a fireball can be shot.
  ViewAngle float64 `json:"view_angle,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
