package component

// Code generated by scrapper/entityBp.ts;

// Allows the entity to search within an area for farmland with air above it. If found, the entity will replace the air block by planting a seed item from its inventory on the farmland block. This goal requires "minecraft:inventory" and "minecraft:navigation" to execute. This goal will not execute if the entity does not have an item in its inventory.  
type Behavior_HarvestFarmBlock struct {
  // Distance in blocks within the entity considers it has reached it's target position. 
  GoalRadius *float64 `json:"goal_radius,omitempty"`
  // The maximum amount of time in seconds that the goal can take before searching for the first harvest block. The time is chosen between 0 and this number.
  MaxSecondsBeforeSearch *float64 `json:"max_seconds_before_search,omitempty"`
  // The maximum amount of time in seconds that the goal can take before searching again, after failing to find a a harvest block already. The time is chosen between 0 and this number.
  SearchCooldownMaxSeconds *float64 `json:"search_cooldown_max_seconds,omitempty"`
  // The number of randomly selected blocks each tick that the entity will check within its search range and height for a valid block to move to. A value of 0 will have the mob check every block within range in one tick.
  SearchCount int `json:"search_count,omitempty"`
  // The Height in blocks the entity will search within to find a valid target position.
  SearchHeight *int `json:"search_height,omitempty"`
  // The distance in blocks the entity will search within to find a valid target position.
  SearchRange *int `json:"search_range,omitempty"`
  // The amount of time in seconds that the goal will cooldown after a successful reap/sow, before it can start again.
  SecondsUntilNewTask *float64 `json:"seconds_until_new_task,omitempty"`
  // Movement speed multiplier of the entity when using this Goal.
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
