package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to look around for another mob to ride atop it.  
type Behavior_FindMount struct {
  // If true, the mob will not go into water blocks when going towards a mount
  AvoidWater bool `json:"avoid_water,omitempty"`
  // This is the distance the mob needs to be, in blocks, from the desired mount to mount it. If the value is below 0, the mob will use its default attack distance
  MountDistance float64 `json:"mount_distance,omitempty"`
  // Time the mob will wait before starting to move towards the mount
  StartDelay int `json:"start_delay,omitempty"`
  // If true, the mob will only look for a mount if it has a target
  TargetNeeded bool `json:"target_needed,omitempty"`
  // Distance in blocks within which the mob will look for a mount
  WithinRadius float64 `json:"within_radius,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
