package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to stay at a certain level when in liquid.  
type Behavior_RiseToLiquidLevel struct {
  // Target distance down from the liquid surface. i.e. Positive values move the target Y down.
  LiquidYOffset float64 `json:"liquid_y_offset,omitempty"`
  // Movement up in Y per tick when below the liquid surface.
  RiseDelta float64 `json:"rise_delta,omitempty"`
  // Movement down in Y per tick when above the liquid surface.
  SinkDelta float64 `json:"sink_delta,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
