package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to follow their parent around.  
type Behavior_FollowParent struct {
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
