package component

// Code generated by scrapper/entityBp.ts;

// Fires an event when this behavior starts, then waits for a duration before stopping. When stopping due to that timeout or due to being interrupted by another behavior, fires another event. query.timer_flag_3 will return 1.0 on both the client and server when this behavior is running, and 0.0 otherwise.  
type Behavior_TimerFlag3 struct {
  // Goal cooldown range in seconds
  CooldownRange *float64 `json:"cooldown_range,omitempty"`
  // Goal duration range in seconds
  DurationRange *float64 `json:"duration_range,omitempty"`
  // [Trigger] Event(s) to run when the goal end.
  OnEnd interface{} `json:"on_end,omitempty"`
  // [Trigger] Event(s) to run when the goal starts.
  OnStart interface{} `json:"on_start,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
