package component

// Code generated by scrapper/entityBp.ts;

// Allows this mob to break doors.
type Behavior_BreakDoor struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
