package component

// Code generated by scrapper/entityBp.ts;

// Allows a mob to randomly fly around.  
type Behavior_RandomFly struct {
  // If true, the mob can stop flying and land on a tree instead of the ground
  CanLandOnTrees bool `json:"can_land_on_trees,omitempty"`
  // Distance in blocks on ground that the mob will look for a new spot to move to. Must be at least 1
  XzDist int `json:"xz_dist,omitempty"`
  // Distance in blocks that the mob will look up or down for a new spot to move to. Must be at least 1
  YDist int `json:"y_dist,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
