package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to be tempted by food they like.  
type Behavior_Tempt struct {
  // If true, the mob can stop being tempted if the player moves too fast while close to this mob
  CanGetScared bool `json:"can_get_scared,omitempty"`
  // If true, vertical distance to the player will be considered when tempting.
  CanTemptVertically bool `json:"can_tempt_vertically,omitempty"`
  // If true, the mob can be tempted even if it has a passenger (i.e. if being ridden).
  CanTemptWhileRidden bool `json:"can_tempt_while_ridden,omitempty"`
  // List of items this mob is tempted by
  Items []interface{} `json:"items,omitempty"`
  // Range of random ticks to wait between tempt sounds.
  SoundInterval *float64 `json:"sound_interval,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // Sound to play while the mob is being tempted.
  TemptSound string `json:"tempt_sound,omitempty"`
  // Distance in blocks this mob can get tempted by a player holding an item they like
  WithinRadius float64 `json:"within_radius,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
