package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to inspect bookshelves.  
type Behavior_InspectBookshelf struct {
  // Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot
  GoalRadius float64 `json:"goal_radius,omitempty"`
  // The number of blocks each tick that the mob will check within its search range and height for a valid block to move to. A value of 0 will have the mob check every block within range in one tick
  SearchCount int `json:"search_count,omitempty"`
  // The height that the mob will search for bookshelves
  SearchHeight int `json:"search_height,omitempty"`
  // Distance in blocks the mob will look for books to inspect
  SearchRange int `json:"search_range,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
