package component

// Code generated by scrapper/entityBp.ts;

// Allows the enderman to take a block and carry it around. Can only be used by Endermen.
type Behavior_EndermanTakeBlock struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
