package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to move to a POI if able to  
type Behavior_MoveToPoi struct {
  // Tells the goal what POI type it should be looking for
  PoiType string `json:"poi_type,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
