package component

// Code generated by scrapper/entityBp.ts;

// Enables the mob to admire items that have been configured as admirable. Must be used in combination with the admire_item component  
type Behavior_AdmireItem struct {
  // The sound event to play when admiring the item
  AdmireItemSound string `json:"admire_item_sound,omitempty"`
  // The range of time in seconds to randomly wait before playing the sound again.
  SoundInterval float64 `json:"sound_interval,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
