package component

// Code generated by scrapper/entityBp.ts;

// Enables the mob to barter for items that have been configured as barter currency. Must be used in combination with the barter component
type Behavior_Barter struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
