package component

// Code generated by scrapper/entityBp.ts;

// Allows the squid to stick to the ground when outside water. Can only be used by the Squid.
type Behavior_SquidOutOfWater struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
