package component

// Code generated by scrapper/entityBp.ts;

// Allows this entity to dig into the ground before despawning.  
type Behavior_Dig struct {
  // If true, this behavior can run when this entity is named. Otherwise not.
  AllowDigWhenNamed bool `json:"allow_dig_when_named,omitempty"`
  // Indicates that the actor should start digging when it sees daylight
  DigsInDaylight bool `json:"digs_in_daylight,omitempty"`
  // Goal duration in seconds
  Duration float64 `json:"duration,omitempty"`
  // The minimum idle time in seconds between the last detected disturbance to the start of digging.
  IdleTime float64 `json:"idle_time,omitempty"`
  // [Trigger] Event(s) to run when the goal starts.
  OnStart interface{} `json:"on_start,omitempty"`
  // If true, finding new suspicious locations count as disturbances that may delay the start of this goal.
  SuspicionIsDisturbance bool `json:"suspicion_is_disturbance,omitempty"`
  // If true, vibrations count as disturbances that may delay the start of this goal.
  VibrationIsDisturbance bool `json:"vibration_is_disturbance,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
