package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to stay indoors during night time.
type Behavior_RestrictOpenDoor struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
