package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to automatically start avoiding the sun when its a clear day out.
type Behavior_RestrictSun struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
