package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to open and close doors.
type Behavior_DoorInteract struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
