package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to be ridden by the player after being tamed.
type Behavior_PlayerRideTamed struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
