package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to move into a random location within a village within the search range.  
type Behavior_StrollTowardsVillage struct {
  // Time in seconds the mob has to wait before using the goal again
  CooldownTime float64 `json:"cooldown_time,omitempty"`
  // Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot
  GoalRadius float64 `json:"goal_radius,omitempty"`
  // The distance in blocks to search for points inside villages. If <= 0, find the closest village regardless of distance.
  SearchRange int `json:"search_range,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier float64 `json:"speed_multiplier,omitempty"`
  // This is the chance that the mob will start this goal, from 0 to 1
  StartChance float64 `json:"start_chance,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
