package component

// Code generated by scrapper/entityBp.ts;

// The entity puts on the desired equipment.
type Behavior_EquipItem struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
