package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to look at a player that is holding a tradable item.  
type Behavior_TradeInterest struct {
  // The max time in seconds that the trader will hold an item before attempting to switch for a different item that takes the same trade
  CarriedItemSwitchTime float64 `json:"carried_item_switch_time,omitempty"`
  // The time in seconds before the trader can use this goal again
  Cooldown float64 `json:"cooldown,omitempty"`
  // The max time in seconds that the trader will be interested with showing its trade items
  InterestTime float64 `json:"interest_time,omitempty"`
  // The max time in seconds that the trader will wait when you no longer have items to trade
  RemoveItemTime float64 `json:"remove_item_time,omitempty"`
  // Distance in blocks this mob can be interested by a player holding an item they like
  WithinRadius float64 `json:"within_radius,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
