package component

// Code generated by scrapper/entityBp.ts;

// Allows the dragon to look around for a player to attack while in perch mode. Can only be used by the Ender Dragon.
type Behavior_Dragonscanning struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
