package component

// Code generated by scrapper/entityBp.ts;

// Allows the squid to move away from ground blocks and back to water. Can only be used by the Squid.
type Behavior_SquidMoveAwayFromGround struct {
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
