package component

// Code generated by scrapper/entityBp.ts;

// Allows the mob to enter the panic state, which makes it run around and away from the damage source that made it enter this state.  
type Behavior_Panic struct {
  // The list of Entity Damage Sources that will cause this mob to panic
  DamageSources *[]interface{} `json:"damage_sources,omitempty"`
  // If true, this mob will not stop panicking until it can't move anymore or the goal is removed from it
  Force bool `json:"force,omitempty"`
  // If true, the mob will not panic in response to damage from other mobs. This overrides the damage types in "damage_sources"
  IgnoreMobDamage bool `json:"ignore_mob_damage,omitempty"`
  // If true, the mob will prefer water over land
  PreferWater bool `json:"prefer_water,omitempty"`
  // Movement speed multiplier of the mob when using this AI Goal
  SpeedMultiplier *float64 `json:"speed_multiplier,omitempty"`
  // The priority of this behavior. Lower values are higher priority.
  Priority int `json:"priority,omitempty"`
}
