package component

// Code generated by scrapper/entityBp.ts;

// The current state of the boss for updating the boss HUD.  
type Boss struct {
  // The max distance from the boss at which the boss's health bar is present on the players screen.
  HudRange *int `json:"hud_range,omitempty"`
  // The name that will be displayed above the boss's health bar.
  Name string `json:"name,omitempty"`
  // Whether the sky should darken in the presence of the boss.
  ShouldDarkenSky bool `json:"should_darken_sky,omitempty"`
}
