package component

// Code generated by scrapper/entityBp.ts;

// Specifies the blocks that this entity can break as it moves around.  
type BreakBlocks struct {
  // A list of the blocks that can be broken as this entity moves around
  BreakableBlocks []interface{} `json:"breakable_blocks,omitempty"`
}
