package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// Specifies hunt celebration behaviour.  
type CelebrateHunt struct {
  // If true, celebration will be broadcasted to other entities in the radius.
  Broadcast *bool `json:"broadcast,omitempty"`
  // The list of conditions that target of hunt must satisfy to initiate celebration.
  CeleberationTargets *f.Filter `json:"celeberation_targets,omitempty"`
  // The sound event to play when the mob is celebrating
  CelebrateSound string `json:"celebrate_sound,omitempty"`
  // Duration, in seconds, of celebration
  Duration *int `json:"duration,omitempty"`
  // If broadcast is enabled, specifies the radius in which it will notify other entities for celebration.
  Radius *float64 `json:"radius,omitempty"`
  // The range of time in seconds to randomly wait before playing the sound again
  SoundInterval float64 `json:"sound_interval,omitempty"`
}
