package component

// Code generated by scrapper/entityBp.ts;

// Defines the entity's color. Only works on vanilla entities that have predefined color values (sheep, llama, shulker).  
type Color struct {
  // The Palette Color value of the entity.
  Value int `json:"value,omitempty"`
}
