package component

// Code generated by scrapper/entityBp.ts;

// Defines the entity's second texture color. Only works on vanilla entities that have a second predefined color values (tropical fish).  
type Color2 struct {
  // The second Palette Color value of the entity.
  Value int `json:"value,omitempty"`
}
