package component

// Code generated by scrapper/entityBp.ts;

// Gives Regeneration I and removes Mining Fatigue from the mob that kills the Actor's attack target.  
type CombatRegeneration struct {
  // Determines if the mob will grant mobs of the same type combat buffs if they kill the target.
  ApplyToFamily bool `json:"apply_to_family,omitempty"`
  // Determines if the mob will grant itself the combat buffs if it kills the target.
  ApplyToSelf bool `json:"apply_to_self,omitempty"`
  // The duration in seconds of Regeneration I added to the mob.
  RegenerationDuration int `json:"regeneration_duration,omitempty"`
}
