package component

// Code generated by scrapper/entityBp.ts;

// Defines the Conditional Spatial Update Bandwidth Optimizations of this entity.  
type ConditionalBandwidthOptimization struct {
  // The object containing the conditional bandwidth optimization values.conditional_values#
  ConditionalValues []interface{} `json:"conditional_values,omitempty"`
  // The object containing the default bandwidth optimization values.max_dropped_ticks#
  DefaultValues interface{} `json:"default_values,omitempty"`
}
