package component

// Code generated by scrapper/entityBp.ts;

// List of hitboxes for melee and ranged hits against the entity.  
type CustomHitTest struct {
  // Comma seperated list of hitboxes.
  Hitboxes []interface{} `json:"hitboxes,omitempty"`
}
