package component

// Code generated by scrapper/entityBp.ts;

// [Not a component] List of triggers with the events to call when taking specific kinds of damage.
type DamageSensorTriggers struct {
  // Type of damage that triggers the events.
  Cause string `json:"cause,omitempty"`
  // A modifier that adds to/removes from the base damage from the damage cause. It does not reduce damage to less than 0.
  DamageModifier float64 `json:"damage_modifier,omitempty"`
  // A multiplier that modifies the base damage from the damage cause. If deals_damage is true the multiplier can only reduce the damage the entity will take to a minimum of 1.
  DamageMultiplier float64 `json:"damage_multiplier,omitempty"`
  // If true, the damage dealt to the entity will take away health from it, set to false to make the entity ignore that damage.
  DealsDamage bool `json:"deals_damage,omitempty"`
  // Specifies filters for entity definitions and events.
  OnDamage interface{} `json:"on_damage,omitempty"`
  // Defines what sound to play, if any, when the on_damage filters are met.
  OnDamageSoundEvent string `json:"on_damage_sound_event,omitempty"`
}

// Defines what events to call when this entity is damaged by specific entities or items.  
type DamageSensor struct {
  // List of triggers with the events to call when taking specific kinds of damage.
  Triggers []DamageSensorTriggers `json:"triggers,omitempty"`
}
