package component

// Code generated by scrapper/entityBp.ts;

// Ability for a rideable entity to dash.  
type Dash struct {
  // The dash cooldown in seconds. Default value is 1.000000.
  CooldownTime *float64 `json:"cooldown_time,omitempty"`
  // Horizontal momentum of the dash.
  HorizontalMomentum *float64 `json:"horizontal_momentum,omitempty"`
  // Vertical momentum of the dash.
  VerticalMomentum *float64 `json:"vertical_momentum,omitempty"`
}
