package component

// Code generated by scrapper/entityBp.ts;

// Sets this entity's default head rotation angle.  
type DefaultLookAngle struct {
  // Angle in degrees.
  Value *float64 `json:"value,omitempty"`
}
