package component

// Code generated by scrapper/entityBp.ts;

// Creates a trigger based on environment conditions.  
type EnvironmentSensor struct {
  // The list of triggers that fire when the environment conditions match the given filter criteria.
  Triggers []interface{} `json:"triggers,omitempty"`
}
