package component

// Code generated by scrapper/entityBp.ts;

// The entity puts on the desired equipment.  
type EquipItem struct {
  // List of items that the entity should not equip.
  ExcludedItems []interface{} `json:"excluded_items,omitempty"`
}
