package component

// Code generated by scrapper/entityBp.ts;

// [Not a component] List of slots and the item that can be equipped.
type EquippableSlots struct {
  // The list of items that can go in this slot.
  AcceptedItems []interface{} `json:"accepted_items,omitempty"`
  // Text to be displayed when the entity can be equipped with this item when playing with Touch-screen controls.
  InteractText string `json:"interact_text,omitempty"`
  // Identifier of the item that can be equipped for this slot.
  Item string `json:"item,omitempty"`
  // Event to trigger when this entity is equipped with this item.
  OnEquip string `json:"on_equip,omitempty"`
  // Event to trigger when this item is removed from this entity.
  OnUnequip string `json:"on_unequip,omitempty"`
  // The slot number of this slot.
  Slot int `json:"slot,omitempty"`
}

// Defines an entity's behavior for having items equipped to it.  
type Equippable struct {
  // List of slots and the item that can be equipped.
  Slots []EquippableSlots `json:"slots,omitempty"`
}
