package component

// Code generated by scrapper/entityBp.ts;

// .  
type ExperienceReward struct {
  // [Molang String] A Molang expression defining the amount of experience rewarded when this entity is successfully bred. An array of expressions adds each expression's result together for a final total.
  OnBred string `json:"on_bred,omitempty"`
  // [Molang String] A Molang expression defining the amount of experience rewarded when this entity dies. An array of expressions adds each expression's result together for a final total.
  OnDeath string `json:"on_death,omitempty"`
}
