package component

// Code generated by scrapper/entityBp.ts;

// Allows entities to flock in groups in water or not.  
type Flocking struct {
  // The amount of blocks away the entity will look at to push away from.
  BlockDistance float64 `json:"block_distance,omitempty"`
  // The weight of the push back away from blocks.
  BlockWeight float64 `json:"block_weight,omitempty"`
  // The amount of push back given to a flocker that breaches out of the water.
  BreachInfluence float64 `json:"breach_influence,omitempty"`
  // The threshold in which to start applying cohesion.
  CohesionThreshold *float64 `json:"cohesion_threshold,omitempty"`
  // The weight applied for the cohesion steering of the flock.
  CohesionWeight *float64 `json:"cohesion_weight,omitempty"`
  // The weight on which to apply on the goal output.
  GoalWeight float64 `json:"goal_weight,omitempty"`
  // Determines the high bound amount of entities that can be allowed in the flock.
  HighFlockLimit int `json:"high_flock_limit,omitempty"`
  // Tells the Flocking Component if the entity exists in water.
  InWater bool `json:"in_water,omitempty"`
  // The area around the entity that allows others to be added to the flock.
  InfluenceRadius float64 `json:"influence_radius,omitempty"`
  // The distance in which the flocker will stop applying cohesion.
  InnnerCohesionThreshold float64 `json:"innner_cohesion_threshold,omitempty"`
  // The percentage chance between 0-1 that a fish will spawn and not want to join flocks. Invalid values will be capped at the end points.
  LonerChance float64 `json:"loner_chance,omitempty"`
  // Determines the low bound amount of entities that can be allowed in the flock.
  LowFlockLimit int `json:"low_flock_limit,omitempty"`
  // Tells the flockers that they can only match similar entities that also match the variant, mark variants, and color data of the other potential flockers.
  MatchVariants bool `json:"match_variants,omitempty"`
  // The max height allowable in the air or water.
  MaxHeight float64 `json:"max_height,omitempty"`
  // The min height allowable in the air or water.
  MinHeight float64 `json:"min_height,omitempty"`
  // The distance that is determined to be to close to another flocking and to start applying separation.
  SeparationThreshold *float64 `json:"separation_threshold,omitempty"`
  // The weight applied to the separation of the flock.
  SeparationWeight *float64 `json:"separation_weight,omitempty"`
  // Tells the flockers that they will follow flocks based on the center of mass.
  UseCenterOfMass bool `json:"use_center_of_mass,omitempty"`
}
