package component

// Code generated by scrapper/entityBp.ts;

// Speed in Blocks that this entity flies at.  
type FlyingSpeed struct {
  // Flying speed in blocks per tick.
  Value *float64 `json:"value,omitempty"`
}
