package component

// Code generated by scrapper/entityBp.ts;

// Defines how much friction affects this entity.  
type FrictionModifier struct {
  // The higher the number, the more the friction affects this entity. A value of 1.0 means regular friction, while 2.0 means twice as much.
  Value *float64 `json:"value,omitempty"`
}
