package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// Keeps track of entity group size in the given radius.  
type GroupSize struct {
  // The list of conditions that must be satisfied for other entities to be counted towards group size.
  Filters *f.Filter `json:"filters,omitempty"`
  // Radius from center of entity.
  Radius float64 `json:"radius,omitempty"`
}
