package component

// Code generated by scrapper/entityBp.ts;

// Sets the offset from the ground that the entity is actually at.  
type GroundOffset struct {
  // The value of the entity's offset from the terrain, in blocks.
  Value float64 `json:"value,omitempty"`
}
