package component

// Code generated by scrapper/entityBp.ts;

// Defines the health of this entity.
type Health struct {
    // The amount of health the entity has.
    Value int `json:"value,omitempty"`

    // The maximum amount of health the entity can have.
    Max int `json:"max,omitempty"`

    // The minimum amount of health the entity can have.
    Min int `json:"min,omitempty"`

}