package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// [Not a component] The array of items that can be used to heal this entity.
type HealableItems struct {
  // The amount of health this entity gains when fed this item.
  HealAmount int `json:"heal_amount,omitempty"`
  // Item identifier that can be used to heal this entity.
  Item string `json:"item,omitempty"`
}

// Defines the interactions with this entity for healing it.  
type Healable struct {
  // The filter group that defines the conditions for using this item to heal the entity.
  Filters *f.Filter `json:"filters,omitempty"`
  // Determines if item can be used regardless of entity being at full health.
  ForceUse bool `json:"force_use,omitempty"`
  // The array of items that can be used to heal this entity.
  Items []HealableItems `json:"items,omitempty"`
}
