package component

// Code generated by scrapper/entityBp.ts;

// Saves a home pos for when the the entity is spawned.  
type Home struct {
  // Optional block list that the home position will be associated with. If any of the blocks no longer exist at that position, the home restriction is removed. Example syntax: minecraft:sand.  Not supported: minecraft:sand:1
  HomeBlockList []interface{} `json:"home_block_list,omitempty"`
  // The radius that the entity will be restricted to in relation to its home
  RestrictionRadius int `json:"restriction_radius,omitempty"`
}
