package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// Defines a set of conditions under which an entity should take damage.  
type HurtOnCondition struct {
  // List of damage conditions that when met can cause damage to the entity.cause#
  DamageConditions []interface{} `json:"damage_conditions,omitempty"`
}

// List of damage conditions that when met can cause damage to the entity.
type HurtOnConditionDamageConditions struct {
    // The kind of damage that is caused to the entity. Various armors and spells use this to determine if the entity is immune.
    Cause string `json:"cause,omitempty"`

    // The amount of damage done each tick that the conditions are met.
    DamagePerTick int `json:"damage_per_tick,omitempty"`

    // The set of conditions that must be satisfied before the entity takes the defined damage.
    Filters *f.Filter `json:"filters,omitempty"`

}