package component

// Code generated by scrapper/entityBp.ts;

// When configured as a rideable entity, the entity will be controlled using WASD controls. Beginning with 1.19.50 the default auto step height for rideable entities is half a block. Consider adding the `variable_max_auto_step` component to increase it.
type InputGroundControlled struct {
}
