package component

// Code generated by scrapper/entityBp.ts;

// Verifies whether the entity is inside any of the listed blocks.  
type InsideBlockNotifier struct {
  // List of blocks, with certain block states, that we are monitoring to see if the entity is inside.
  BlockList []interface{} `json:"block_list,omitempty"`
}
