package component

// Code generated by scrapper/entityBp.ts;

// Adds a timer since last rested to see if phantoms should spawn.  
type Insomnia struct {
  // Number of days the mob has to stay up until the insomnia effect begins.
  DaysUntilInsomnia float64 `json:"days_until_insomnia,omitempty"`
}
