package component

// Code generated by scrapper/entityBp.ts;

// Despawns the Actor immediately.  
type InstantDespawn struct {
  // If true, all entities linked to this entity in a child relationship (eg. leashed) will also be despawned.
  RemoveChildEntities bool `json:"remove_child_entities,omitempty"`
}
