package component

// Code generated by scrapper/entityBp.ts;

// Allows dyes to be used on this entity to change its color.  
type IsDyeable struct {
  // The text that will display when interacting with this entity with a dye when playing with Touch-screen controls.
  InteractText string `json:"interact_text,omitempty"`
}
