package component

// Code generated by scrapper/entityBp.ts;

// Defines what items can be used to control this entity while ridden.  
type ItemControllable struct {
  // List of items that can be used to control this entity.
  ControlItems []interface{} `json:"control_items,omitempty"`
}
