package component

// Code generated by scrapper/entityBp.ts;

// Defines a dynamic type jump control that will change jump properties based on the speed modifier of the mob.
type Jump_Dynamic struct {
}
