package component

// Code generated by scrapper/entityBp.ts;

// Gives the entity the ability to jump.  
type Jump_Static struct {
  // The initial vertical velocity for the jump
  JumpPower *float64 `json:"jump_power,omitempty"`
}
