package component

// Code generated by scrapper/entityBp.ts;

// Defines the knockback resistance for this entity.
type KnockbackResistance struct {
    // The knockback resistance of the entity.
    Value float64 `json:"value,omitempty"`

}