package component

// Code generated by scrapper/entityBp.ts;

// Additional variant value. Can be used to further differentiate variants.  
type MarkVariant struct {
  // The ID of the variant. By convention, 0 is the ID of the base entity.
  Value int `json:"value,omitempty"`
}
