package component

// Code generated by scrapper/entityBp.ts;

// This move control allows a mob to fly, swim, climb, etc.  
type Movement_Generic struct {
  // The maximum number in degrees the mob can turn per tick.
  MaxTurn float64 `json:"max_turn,omitempty"`
}
