package component

// Code generated by scrapper/entityBp.ts;

// This move control causes the mob to hover.  
type Movement_Hover struct {
  // The maximum number in degrees the mob can turn per tick.
  MaxTurn *float64 `json:"max_turn,omitempty"`
}
