package component

// Code generated by scrapper/entityBp.ts;

// This component accents the movement of an entity.  
type Movement_Basic struct {
  // The maximum number in degrees the mob can turn per tick.
  MaxTurn *float64 `json:"max_turn,omitempty"`
}
