package component

// Code generated by scrapper/entityBp.ts;

// Defines the movement speed for this entity.
type Movement struct {
    // The speed of the entity.
    Value float64 `json:"value,omitempty"`

}