package component

// Code generated by scrapper/entityBp.ts;

// This move control causes the mob to fly.  
type Movement_Fly struct {
  // The maximum number in degrees the mob can turn per tick.
  MaxTurn float64 `json:"max_turn,omitempty"`
}
