package component

// Code generated by scrapper/entityBp.ts;

// Defines physics properties of an actor, including if it is affected by gravity or if it collides with objects.  
type Physics struct {
  // Whether or not the object collides with things.
  HasCollision *bool `json:"has_collision,omitempty"`
  // Whether or not the entity is affected by gravity.
  HasGravity *bool `json:"has_gravity,omitempty"`
  // Whether or not the entity should be pushed towards the nearest open area when stuck inside a block.
  PushTowardsClosestSpace bool `json:"push_towards_closest_space,omitempty"`
}
