package component

// Code generated by scrapper/entityBp.ts;

// Specifies costing information for mobs that prefer to walk on preferred paths.  
type PreferredPath struct {
  // Cost for non-preferred blocks
  DefaultBlockCost float64 `json:"default_block_cost,omitempty"`
  // Added cost for jumping up a node
  JumpCost int `json:"jump_cost,omitempty"`
  // Distance mob can fall without taking damage
  MaxFallBlocks *int `json:"max_fall_blocks,omitempty"`
  // A list of blocks with their associated cost
  PreferredPathBlocks []interface{} `json:"preferred_path_blocks,omitempty"`
}
