package component

// Code generated by scrapper/entityBp.ts;

// Sets the distance through which the entity can push through.  
type PushThrough struct {
  // The value of the entity's push-through, in blocks.
  Value float64 `json:"value,omitempty"`
}
