package component

// Code generated by scrapper/entityBp.ts;

// Defines what can push an entity between other entities and pistons.  
type Pushable struct {
  // Whether the entity can be pushed by other entities.
  IsPushable *bool `json:"is_pushable,omitempty"`
  // Whether the entity can be pushed by pistons safely.
  IsPushableByPiston *bool `json:"is_pushable_by_piston,omitempty"`
}
