package component

// Code generated by scrapper/entityBp.ts;

// Attempts to trigger a raid at the entity's location.  
type RaidTrigger struct {
  // Event to run when a raid is triggered on the village.
  TriggeredEvent string `json:"triggered_event,omitempty"`
}
