package component

// Code generated by scrapper/entityBp.ts;

//  
type RailSensor struct {
  // If true, on tick this entity will trigger its on_deactivate behavior
  CheckBlockTypes bool `json:"check_block_types,omitempty"`
  // If true, this entity will eject all of its riders when it passes over an activated rail
  EjectOnActivate bool `json:"eject_on_activate,omitempty"`
  // If true, this entity will eject all of its riders when it passes over a deactivated rail
  EjectOnDeactivate bool `json:"eject_on_deactivate,omitempty"`
  // Event to call when the rail is activated
  OnActivate string `json:"on_activate,omitempty"`
  // Event to call when the rail is deactivated
  OnDeactivate string `json:"on_deactivate,omitempty"`
  // If true, command blocks will start ticking when passing over an activated rail
  TickCommandBlockOnActivate bool `json:"tick_command_block_on_activate,omitempty"`
  // If false, command blocks will stop ticking when passing over a deactivated rail
  TickCommandBlockOnDeactivate bool `json:"tick_command_block_on_deactivate,omitempty"`
}
