package component

// Code generated by scrapper/entityBp.ts;

// Defines the ravager's response to their melee attack being blocked.  
type RavagerBlocked struct {
  // The strength with which blocking entities should be knocked back
  KnockbackStrength *float64 `json:"knockback_strength,omitempty"`
  // A list of weighted responses to the melee attack being blocked
  ReactionChoices *[]interface{} `json:"reaction_choices,omitempty"`
}
