package component

// Code generated by scrapper/entityBp.ts;

// Sets the entity's visual size.  
type Scale struct {
  // The value of the scale. 1.0 means the entity will appear at the scale they are defined in their model. Higher numbers make the entity bigger.
  Value *float64 `json:"value,omitempty"`
}
