package component

// Code generated by scrapper/entityBp.ts;

// Fires off scheduled mob events at time of day events.  
type Scheduler struct {
  // The list of triggers that fire when the conditions match the given filter criteria. If any filter criteria overlap the first defined event will be picked.
  ScheduledEvents []interface{} `json:"scheduled_events,omitempty"`
}
