package component

// Code generated by scrapper/entityBp.ts;

// Skin ID value. Can be used to differentiate skins, such as base skins for villagers.  
type SkinId struct {
  // The ID of the skin. By convention, 0 is the ID of the base skin.
  Value int `json:"value,omitempty"`
}
