package component

// Code generated by scrapper/entityBp.ts;

// Sets the entity's base volume for sound effects.  
type SoundVolume struct {
  // The value of the volume the entity uses for sound effects.
  Value *float64 `json:"value,omitempty"`
}
