package component

// Code generated by scrapper/entityBp.ts;

// [Not a component] List of effects to add to this entity after adding this component
type SpellEffectsAddEffects struct {
  // Effect to add to this entity. Includes 'duration' in seconds, 'amplifier' level, 'ambient' if it is to be considered an ambient effect, and 'visible' if the effect should be visible
  Effect string `json:"effect,omitempty"`
}

// Defines what mob effects to add and remove to the entity when adding this component.  
type SpellEffects struct {
  // List of effects to add to this entity after adding this component
  AddEffects []SpellEffectsAddEffects `json:"add_effects,omitempty"`
  // List of identifiers of effects to be removed from this entity after adding this component
  RemoveEffects string `json:"remove_effects,omitempty"`
}
