package component

// Code generated by scrapper/entityBp.ts;

// Defines the entity's range within which it can see or sense other entities to target them.  
type TargetNearbySensor struct {
  // Maximum distance in blocks that another entity will be considered in the 'inside' range
  InsideRange float64 `json:"inside_range,omitempty"`
  // Whether the other entity needs to be visible to trigger 'inside' events
  MustSee bool `json:"must_see,omitempty"`
  // Event to call when an entity gets in the inside range. Can specify 'event' for the name of the event and 'target' for the target of the event
  OnInsideRange string `json:"on_inside_range,omitempty"`
  // Event to call when an entity gets in the outside range. Can specify 'event' for the name of the event and 'target' for the target of the event
  OnOutsideRange string `json:"on_outside_range,omitempty"`
  // Event to call when an entity exits visual range. Can specify 'event' for the name of the event and 'target' for the target of the event
  OnVisionLostInsideRange string `json:"on_vision_lost_inside_range,omitempty"`
  // Maximum distance in blocks that another entity will be considered in the 'outside' range
  OutsideRange float64 `json:"outside_range,omitempty"`
}
