package component

// Code generated by scrapper/entityBp.ts;

// Defines this entity's ability to trade with players.  
type TradeTable struct {
  // Determines when the mob transforms, if the trades should be converted when the new mob has a economy_trade_table. When the trades are converted, the mob will generate a new trade list with their new trade table, but then it will try to convert any of the same trades over to have the same enchantments and user data. For example, if the original has a Emerald to Enchanted Iron Sword (Sharpness 1), and the new trade also has an Emerald for Enchanted Iron Sword, then the enchantment will be Sharpness 1.
  ConvertTradesEconomy bool `json:"convert_trades_economy,omitempty"`
  // Name to be displayed while trading with this entity.
  DisplayName string `json:"display_name,omitempty"`
  // Used to determine if trading with entity opens the new trade screen.
  NewScreen bool `json:"new_screen,omitempty"`
  // Determines if the trades should persist when the mob transforms. This makes it so that the next time the mob is transformed to something with a trade_table or economy_trade_table, then it keeps their trades.
  PersistTrades bool `json:"persist_trades,omitempty"`
  // File path relative to the behavior pack root for this entity's trades.
  Table string `json:"table,omitempty"`
}
