package component

// Code generated by scrapper/entityBp.ts;

import (
  f "github.com/respectZ/glowstone/bp/types"
)

// Causes an entity to leave a trail of blocks as it moves about the world.  
type Trail struct {
  // The type of block you wish to be spawned by the entity as it move about the world. Solid blocks may not be spawned at an offset of (0,0,0).
  BlockType string `json:"block_type,omitempty"`
  // One or more conditions that must be met in order to cause the chosen block type to spawn.
  SpawnFilter *f.Filter `json:"spawn_filter,omitempty"`
  // [Vector3 [a,b,c]] The distance from the entities current position to spawn the block. Capped at up to 16 blocks away. The X value is left/right(-/+), the Z value is backward/forward(-/+), the Y value is below/above(-/+).
  SpawnOffset []float64 `json:"spawn_offset,omitempty"`
}
