package component

// Code generated by scrapper/entityBp.ts;

// Defines the families this entity belongs to.  
type TypeFamily struct {
  // List of family names.
  Family []interface{} `json:"family,omitempty"`
}
