package component

// Code generated by scrapper/entityBp.ts;

// Used to differentiate the component group of a variant of an entity from others. (e.g. ocelot, villager)  
type Variant struct {
  // The ID of the variant. By convention, 0 is the ID of the base entity.
  Value int `json:"value,omitempty"`
}
