package component

// Code generated by scrapper/entityBp.ts;

//  
type WaterMovement struct {
  // Drag factor to determine movement speed when in water.
  DragFactor float64 `json:"drag_factor,omitempty"`
}
