package component

// Code generated by scrapper/item/main.ts;

// Determine whether an item can be placed in the off-hand slot of the inventory.
type AllowOffHand struct {
  // Whether the item can be placed in the off-hand slot.
  Value bool `json:"value,omitempty"`

}


