package component

// Code generated by scrapper/item/main.ts;

// Block Placer item component. Items with this component will place a block when used. Experimental toggles required: Holiday Creator Features (in format versions before 1.20.10).
type BlockPlacer struct {
  // Set the placement block name for the planter item.
  Block string `json:"block,omitempty"`

  // List of block descriptors that contain blocks that this item can be used on. If left empty, all blocks will be allowed. See Custom Item Use Priority for more information on use behavior.
  UseOn []interface{} `json:"use_on,omitempty"`

}


