package component

// Code generated by scrapper/item/main.ts;

// Determines if the item will break blocks in Creative Mode while swinging.
type CanDestroyInCreative struct {
  // Defines whether the item can destroy blocks while in creative.
  Value *bool `json:"value,omitempty"`

}


