package component

// Code generated by scrapper/item/main.ts;

// Allows an item to be used over a duration.
type Chargeable struct {
  // Modifier value to scale the players movement speed when item is in use.
  MovementModifier float64 `json:"movement_modifier,omitempty"`

  // Event trigger for when the item has completed its use duration.
  OnComplete string `json:"on_complete,omitempty"`

}


