package component

// Code generated by scrapper/item/main.ts;

// Cool down time for a component. After use, all items in a specified 'cool down category' become unusable for a determined amount of time defined in the component. In format versions before 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle.
type Cooldown struct {
  // The type of cool down for this item.
  Category string `json:"category,omitempty"`

  // The duration of time (in seconds) items with a matching category will spend cooling down before becoming usable again.
  Duration float64 `json:"duration,omitempty"`

}


