package component

// Code generated by scrapper/item/main.ts;

// Determines how much extra damage the item does on attack.
type Damage struct {
  // How much extra damage the item does on attack. Note that this must be a positive value.
  Value int `json:"value,omitempty"`

}


