package component

// Code generated by scrapper/item/main.ts;

import (
  "github.com/respectZ/glowstone/bp/types"
)

// Digger item. Component put on items that dig.
type Digger struct {
  // Destroy speed per block
  DestroySpeeds []interface{} `json:"destroy_speeds,omitempty"`

  // Trigger for when you dig a block that isn't listed in destroy_speeds
  OnDig *types.Trigger `json:"on_dig,omitempty"`

  // Toggles if the item will be used efficiently
  UseEfficiency bool `json:"use_efficiency,omitempty"`

}


