package component

// Code generated by scrapper/item/main.ts;

// Defines the text shown when an item name is shown, such as hover text. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features' experimental toggle.
type DisplayName struct {
  // Set the display name for an item.
  Value string `json:"value,omitempty"`

}


