package component

// Code generated by scrapper/item/main.ts;

// Allows the item to place specified entities into the world. In format versions prior to 1.20.0, this component requires the 'Holiday Creator Features' experimental toggle.
type EntityPlacer struct {
  // List of block descriptors that contain blocks that this item can be dispensed on. If left empty, all blocks will be allowed.
  DispenseOn []interface{} `json:"dispense_on,omitempty"`

  // The entity to be placed in the world. Note that this parameter is required.
  Entity string `json:"entity,omitempty"`

  // List of block descriptors that contain blocks that this item can be used on. If left empty, all blocks will be allowed.
  UseOn []interface{} `json:"use_on,omitempty"`

}


