package component

// Code generated by scrapper/item/main.ts;

// Determines whether the item has the enchanted glint render effect on it.
type Glint struct {
  // Whether the item has the enchanted glint render effect.
  Value bool `json:"value,omitempty"`

}


