package component

// Code generated by scrapper/item/main.ts;

// Determines if an item is rendered like a tool while in hand.
type HandEquipped struct {
  // Determines if the item is rendered like a tool in-hand.
  Value bool `json:"value,omitempty"`

}


