package component

// Code generated by scrapper/item/main.ts;

// Determines the color of the item name when hovering over it.
type HoverTextColor struct {
  // The color of the item hover text.
  Value interface{} `json:"value,omitempty"`

}


