package component

// Code generated by scrapper/item/main.ts;

// Determines the icon to represent the item in the UI and elsewhere. In format versions before 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle.
type Icon struct {
  // The key from the resource_pack/textures/item_texture.json 'texture_data' object associated with the texture file
  Texture string `json:"texture,omitempty"`

}


