package component

// Code generated by scrapper/item/main.ts;

// A definition of the item, including the 'description' and 'components' sections of the item file.
type Item struct {
  // A list of all components used in this item.
  Components interface{} `json:"components,omitempty"`

  // A written representation of the item. The description must contain an identifier; all other fields are optional.
  Description interface{} `json:"description,omitempty"`

}


