package component

// Code generated by scrapper/item/main.ts;

// Determines whether an item interacts with liquid blocks on use.
type LiquidClipped struct {
  // Whether an item interacts with liquid blocks on use.
  Value bool `json:"value,omitempty"`

}


