package component

// Code generated by scrapper/item/main.ts;

// Determines how many of the item can be stacked.
type MaxStackSize struct {
  // How many of an item that can be stacked together.
  Value int `json:"value,omitempty"`

}


