package component

// Code generated by scrapper/item/main.ts;

// The on_use item component allows you to receive an event when the item is used.
type OnUse struct {
  // Event trigger for when the item is used.
  OnUse interface{} `json:"on_use,omitempty"`

}


