package component

// Code generated by scrapper/item/main.ts;

// The on_use_on item component allows you to receive an event when the item is used on a block in the world
type OnUseOn struct {
  // Event trigger for when the item is used.
  OnUseOn interface{} `json:"on_use_on,omitempty"`

}


