package component

// Code generated by scrapper/item/main.ts;

// Render offsets component: optional values can be given to offset the way the item is rendered.
type RenderOffsets struct {
  // Right hand transform data.
  MainHand []float64 `json:"main_hand,omitempty"`

  // Left hand transform data.
  OffHand []float64 `json:"off_hand,omitempty"`

}


