package component

// Code generated by scrapper/item/main.ts;

// Shooter Item Component. Must have the minecraft:use_modifiers component in order to function properly. In format versions prior to 1.20.10, this component requires the 'Holiday Creator Features' experimental toggle.
type Shooter struct {
  // Sets the entity that is used as ammunition
  Ammunition []interface{} `json:"ammunition,omitempty"`

  // Sets if the item is charged when drawn
  ChargeOnDraw bool `json:"charge_on_draw,omitempty"`

  // Determines how long can the weapon can be drawn before releasing automatically
  MaxDrawDuration float64 `json:"max_draw_duration,omitempty"`

  // When set to 'true', the longer the weapon is drawn, the more power it will have when released
  ScalePowerByDrawDuration bool `json:"scale_power_by_draw_duration,omitempty"`

}

// The 'ammunition' parameter contains four parameters of its own:
type ShooterAmmunition struct {
  // Denotes the item description identifier
  Item string `json:"item,omitempty"`

  // When set to 'true', ammunition can be used from the offhand
  UseOffhand bool `json:"use_offhand,omitempty"`

  // Determines whether the inventory can be searched for ammunition to use
  SearchInventory bool `json:"search_inventory,omitempty"`

  // Determines whether the ammunition can be used in Creative mode
  UseInCreative bool `json:"use_in_creative,omitempty"`

}


