package component

// Code generated by scrapper/item/main.ts;

// Determines whether an item should eventually despawn while floating in the world.
type ShouldDespawn struct {
  // Sets whether the item should eventually despawn while floating in the world.
  Value bool `json:"value,omitempty"`

}


