package component

// Code generated by scrapper/item/main.ts;

// Determines if the same item with different aux values can stack. Additionally, defines whether the item actors can merge while floating in the world.
type StackedByData struct {
  // Sets whether the same item with different aux values can stack and merge while floating in the world.
  Value bool `json:"value,omitempty"`

}


