package component

// Code generated by scrapper/item/main.ts;

// The tags component determines which tags are attached to an item.
type Tags struct {
  // An array which can contain multiple item tags.
  Tags []interface{} `json:"tags,omitempty"`

}


