package component

// Code generated by scrapper/item/main.ts;

// Determines how long an item takes to use in combination with components such as shooter, throwable, or food.
type UseDuration struct {
  // The time it takes, in seconds, to use the item.
  Value float64 `json:"value,omitempty"`

}


