package component

// Code generated by scrapper/item/main.ts;

// Determines which animation plays when using an item.
type UseAnimation struct {
  // Which animation to play when using an item.
  Value string `json:"value,omitempty"`

}


