package component

// Code generated by scrapper/item/main.ts;

// Weapon Item Component. Added to every weapon item such as axe, sword, trident, bow, crossbow.
type Weapon struct {
  // Trigger for letting you know when this item is used to hit a block
  OnHitBlock string `json:"on_hit_block,omitempty"`

  // Trigger for letting you know when this item is used to hurt another mob
  OnHurtEntity string `json:"on_hurt_entity,omitempty"`

  // Trigger for letting you know when this item hit another actor, but didn't do damage
  OnNotHurtEntity string `json:"on_not_hurt_entity,omitempty"`

}


