package component

// Code generated by scrapper/item/main.ts;

// Determines where the item can be worn. If any non-hand slot is chosen, the max stack size is set to 1. Experimental toggles required: Holiday Creator Features.
type Wearable struct {
  // How much protection the wearable has.
  Protection int `json:"protection,omitempty"`

  // Determines where the item can be worn. If any non-hand slot is chosen, the max stack size is set to 1.
  Slot string `json:"slot,omitempty"`

}


